spring:
  application:
    name: java-spring-boot-erudio
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #Por ser ambiente de estudo não irei usar variável de ambiente :D
    url: jdbc:mariadb://localhost:3306/spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
logging:
  level:
    root: info
    sql: info
    com.github.henriquemb: info
springdoc:
  paths-to-match: /api/v1/**
  swagger-ui:
    use-root-path: true